# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=500, verbose_name='key')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u540d\u79f0')),
                ('span', models.FloatField(default=0, help_text='\u5355\u4f4d(\u5c0f\u65f6)', verbose_name='\u5de5\u65f6')),
                ('status', models.CharField(choices=[('pass', '\u901a\u8fc7'), ('unpass', '\u672a\u901a\u8fc7'), ('waiting', '\u7b49\u5f85\u5ba1\u6838')], default='waiting', max_length=20, verbose_name='\u72b6\u6001')),
                ('tag', models.CharField(blank=True, max_length=500, verbose_name='\u6807\u7b7e')),
                ('index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workload.Index', verbose_name='\u76ee\u5f55')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_span', models.FloatField(default=0, help_text='\u5355\u4f4d(\u5c0f\u65f6)', verbose_name='\u8c03\u6574\u5de5\u65f6')),
                ('status', models.CharField(choices=[('pass', '\u901a\u8fc7'), ('unpass', '\u672a\u901a\u8fc7'), ('waiting', '\u7b49\u5f85\u5ba1\u6838')], default='waiting', max_length=20, verbose_name='\u72b6\u6001')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeModel', verbose_name='\u5458\u5de5')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workload.Work', verbose_name='\u5de5\u4f5c')),
            ],
        ),
    ]
