# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='detail',
            field=models.TextField(blank=True, verbose_name='\u8be6\u7ec6'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 4, 18, 13, 5, 36, 14000, tzinfo=utc), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workrecord',
            name='detail',
            field=models.TextField(blank=True, verbose_name='\u8be6\u7ec6'),
        ),
    ]
