# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_auto_20170418_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='key',
        ),
        migrations.AddField(
            model_name='index',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='index',
            name='par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='workload.Index', verbose_name='parent dir'),
        ),
    ]
