# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-21 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_validator


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_auto_20170419_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(default='new index', max_length=500, validators=[helpers.director.model_validator.has_str], verbose_name='name'),
        ),
    ]
