# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_validator


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0004_auto_20170421_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(default='new work', max_length=100, validators=[helpers.director.model_validator.has_str], verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeModel', verbose_name='\u5458\u5de5'),
        ),
    ]
