# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0005_auto_20170423_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='desp_img',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u63cf\u8ff0\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='desp_img',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u63cf\u8ff0\u56fe\u7247'),
        ),
    ]
