# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0009_auto_20170430_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='index',
            new_name='par',
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='count',
            field=models.IntegerField(default=1, help_text='\u6574\u6570', verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='ex_span',
            field=models.FloatField(default=0, help_text='\u5355\u4f4d(\u5c0f\u65f6)\uff0c\u5c0f\u6570\u6216\u6574\u6570', verbose_name='\u8c03\u6574\u5de5\u65f6'),
        ),
    ]
