# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_auto_20170426_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='create time')),
                ('rep_content', models.TextField(blank=True, null=True, verbose_name='reply content')),
                ('pub_type', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=50, verbose_name='publish type')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeModel', verbose_name='employee')),
            ],
        ),
    ]
