# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('rep_content', models.TextField(blank=True, null=True, verbose_name='\u56de\u590d')),
                ('pub_type', models.CharField(choices=[('public', '\u516c\u5f00'), ('private', '\u4fdd\u5bc6')], default='public', max_length=50, verbose_name='\u53d1\u5e03\u7c7b\u578b')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeModel', verbose_name='\u5458\u5de5')),
            ],
        ),
    ]
