# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeModel', verbose_name='\u5458\u5de5'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_type',
            field=models.CharField(choices=[('public', '\u516c\u5f00'), ('private', '\u4fdd\u5bc6')], default='public', max_length=50, verbose_name='\u53d1\u5e03\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rep_content',
            field=models.TextField(blank=True, null=True, verbose_name='\u56de\u590d'),
        ),
    ]
