# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('age', models.CharField(blank=True, max_length=50, verbose_name='age')),
                ('head', models.CharField(blank=True, max_length=200, verbose_name='head image')),
                ('id_number', models.CharField(blank=True, max_length=200, verbose_name='id  number')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='address')),
                ('gen', models.CharField(blank=True, max_length=30, verbose_name='gen')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='phone')),
            ],
            options={
                'verbose_name': 'basic info',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseinfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.BasicInfo', verbose_name='basic info')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
