# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u59d3\u540d')),
                ('age', models.CharField(blank=True, max_length=50, verbose_name='\u5e74\u9f84')),
                ('head', models.CharField(blank=True, default='/static/image/user.jpg', max_length=200, verbose_name='\u5934\u50cf')),
                ('id_number', models.CharField(blank=True, max_length=200, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u7801')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='\u5730\u5740')),
                ('gen', models.CharField(blank=True, choices=[('male', '\u7537'), ('femal', '\u5973')], max_length=30, verbose_name='\u6027\u522b')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='\u7535\u8bdd\u53f7\u7801')),
            ],
            options={
                'verbose_name': '\u57fa\u672c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseinfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.BasicInfo', verbose_name='\u57fa\u672c\u4fe1\u606f')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7')),
            ],
        ),
    ]
