# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'verbose_name': '\u57fa\u672c\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='age',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='gen',
            field=models.CharField(blank=True, choices=[('male', '\u7537'), ('femal', '\u5973')], max_length=30, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='head',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='baseinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.BasicInfo', verbose_name='\u57fa\u672c\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7'),
        ),
    ]
