# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='eid',
            field=models.CharField(default='', max_length=30, verbose_name='employee id'),
        ),
    ]
